site_name: Sorting Visualizer
nav: 
  - Home: index.md
  - Setup: setup.md
  - Visualizer: 
              - Class Visualizer: visualizer.md
              - Module algorithm: algorithm.md
theme: readthedocs
